import Head from 'next/head'
import { useEffect, useState } from 'react'
import { getSiteItems } from '../../contentful/querys/getSiteItem'
import { Box } from '@chakra-ui/react';

export default function Home(props) {
  const [header, setHeader] = useState('');
  const [title, setTitle] = useState('');
  const [footer, setFooter] = useState('');

  useEffect(() => {
    const fetchData = async () => {
      try {
        const { header, title, footer } = await getSiteItems();
        setHeader(header);
        setTitle(title);
        setFooter(footer);

      } catch (error) {
        console.error(error);
      }
    };
  
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main">  
        <Box as="header" bg="brand.100">
          {header}
        </Box>

        <Box as="footer">
          {footer}
        </Box>
      </Box>
    </>
  )
}
